from django.db import models
import datetime

class Counter(models.Model):
    key = models.CharField(max_length=10)
    value = models.IntegerField()
class PCR_data(models.Model):
    date_time = models.DateTimeField(auto_now_add=True, blank=True)
    time = models.CharField(max_length=10)
    call = models.BigIntegerField()
    put = models.BigIntegerField()
    callOI = models.BigIntegerField()
    putOI = models.BigIntegerField()
    diffOI = models.BigIntegerField()
    diff = models.BigIntegerField()
    pcr = models.FloatField()
    pcrOI = models.FloatField()
    option_signal = models.CharField(max_length=10)
    price = models.BigIntegerField()
class Telegram_data(models.Model):
    date_time = models.DateTimeField(auto_now_add=True, blank=True)
    time = models.CharField(max_length=10)
    Nifty_prev = models.FloatField()
    Nifty_new = models.FloatField()
    Count = models.BigIntegerField()
    RSI = models.FloatField()
    Color_code = models.CharField(max_length=10)
    final_signal = models.CharField(max_length=10)

class Telegram_data_past(models.Model):
    date_time = models.DateTimeField(auto_now_add=True, blank=True)
    time = models.CharField(max_length=10)
    Nifty_prev = models.FloatField()
    Nifty_new = models.FloatField()
    Count = models.BigIntegerField()
    RSI = models.FloatField()
    Color_code = models.CharField(max_length=10)
    final_signal = models.CharField(max_length=10)
class PCR_data_past(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True)
    time = models.CharField(max_length=10)
    call = models.BigIntegerField()
    put = models.BigIntegerField()
    callOI = models.BigIntegerField(blank=True,null=True)
    putOI = models.BigIntegerField(blank=True,null=True)
    diffOI = models.BigIntegerField(blank=True,null=True)
    diff = models.BigIntegerField()
    pcr = models.FloatField()
    pcrOI = models.FloatField()
    option_signal = models.CharField(max_length=10)
    price = models.BigIntegerField()
class BTC_Data(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True)
    time = models.CharField(max_length=10)
    RSI = models.FloatField()
    SMA = models.FloatField(blank=True)
    Analysis = models.TextField(blank=True)
    signal = models.BigIntegerField(blank=True,null=True)
    # cond1_buy = models.TextField(blank=True)
    # cond2_buy = models.TextField(blank=True)
    # cond3_buy = models.TextField(blank=True)
    # cond4_sell= models.TextField(blank=True)
    # cond5_sell = models.TextField(blank=True)
    # cond6_sell = models.TextField(blank=True)
    price = models.BigIntegerField(blank=True)
