# Generated by Django 3.2.4 on 2022-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCR_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('call', models.BigIntegerField()),
                ('put', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('pcr', models.BigIntegerField()),
                ('option_signal', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
