# Generated by Django 3.2.16 on 2023-03-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
    ]
