# Generated by Django 4.0.1 on 2022-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCR_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('call', models.BigIntegerField()),
                ('put', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('pcr', models.FloatField()),
                ('pcrOI', models.FloatField()),
                ('option_signal', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PCR_data_past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('call', models.BigIntegerField()),
                ('put', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('pcr', models.FloatField()),
                ('pcrOI', models.FloatField()),
                ('option_signal', models.CharField(max_length=10)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
