# Generated by Django 3.1.1 on 2023-03-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifty_data',
            name='counter_nifty_data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
