# Generated by Django 3.2.4 on 2022-12-16 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_pcr_data_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr_data',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
