# Generated by Django 4.0.1 on 2022-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_pcr_data_calloi_pcr_data_diffoi_pcr_data_putoi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('Nifty_prev', models.FloatField()),
                ('Nifty_new', models.FloatField()),
                ('Count', models.BigIntegerField()),
                ('RSI', models.FloatField()),
                ('Color_code', models.CharField(max_length=10)),
                ('final_signal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_data_past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('Nifty_prev', models.FloatField()),
                ('Nifty_new', models.FloatField()),
                ('Count', models.BigIntegerField()),
                ('RSI', models.FloatField()),
                ('Color_code', models.CharField(max_length=10)),
                ('final_signal', models.CharField(max_length=10)),
            ],
        ),
    ]
