# Generated by Django 4.0.1 on 2022-12-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_pcr_data_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcr_data',
            name='pcr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pcr_data_past',
            name='pcr',
            field=models.FloatField(),
        ),
    ]
