# Generated by Django 4.0.1 on 2023-01-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_telegram_data_telegram_data_past'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('RSI', models.FloatField()),
                ('SMA', models.FloatField(blank=True)),
                ('price', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
