# Generated by Django 4.1.5 on 2023-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0006_btc_data_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="btc_data",
            name="signal",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
