# Generated by Django 4.1.5 on 2023-01-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0008_btc_data_signal_adx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nifty_Data",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("entry_time", models.CharField(max_length=10)),
                ("Nifty_entry", models.FloatField()),
                ("Nifty_exit", models.FloatField(blank=True)),
                ("exit_time", models.CharField(blank=True, max_length=10)),
                ("move", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
