# Generated by Django 4.1.5 on 2023-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0009_nifty_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="nifty_data",
            name="call_put",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
