# Generated by Django 4.1.5 on 2023-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0010_nifty_data_call_put"),
    ]

    operations = [
        migrations.AddField(
            model_name="btc_data",
            name="signal_5min",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
