# Generated by Django 4.1.5 on 2023-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0011_btc_data_signal_5min"),
    ]

    operations = [
        migrations.AddField(
            model_name="btc_data",
            name="price_5min",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
