# Generated by Django 3.2.5 on 2023-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_btc_data_price_5min'),
    ]

    operations = [
        migrations.AddField(
            model_name='btc_data',
            name='signal_adx_5min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
