# Generated by Django 3.2.5 on 2023-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_btc_data_signal_adx_5min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocastic_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('Stocastic_up', models.FloatField()),
                ('Stocastic_down', models.FloatField()),
            ],
        ),
    ]
