# Generated by Django 3.2.5 on 2023-02-08 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0014_stocastic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocastic_data',
            name='ADX',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocastic_data',
            name='Final_call',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
