# Generated by Django 3.2.5 on 2023-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0015_auto_20230208_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocastic_data',
            name='ADX',
        ),
        migrations.RemoveField(
            model_name='stocastic_data',
            name='Final_call',
        ),
        migrations.AlterField(
            model_name='stocastic_data',
            name='Stocastic_down',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stocastic_data',
            name='Stocastic_up',
            field=models.FloatField(blank=True),
        ),
    ]
