# Generated by Django 3.2.5 on 2023-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0016_auto_20230208_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocastic_data',
            name='ADX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocastic_data',
            name='Final_call',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
