# Generated by Django 3.2.16 on 2023-02-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_auto_20230208_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifty_data',
            name='Event_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
