# Generated by Django 3.2.16 on 2023-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0018_nifty_data_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocastic_Data_DXY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.CharField(max_length=10)),
                ('Stocastic_up', models.FloatField(blank=True)),
                ('Stocastic_down', models.FloatField(blank=True)),
                ('ADX', models.FloatField(blank=True, null=True)),
                ('Final_call', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
